---
name: Deploy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry env use $(which python3.11)
          poetry install

      - name: Build package
        run: poetry build

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: built-packages
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      id-token: write

    steps:
      - name: Fetch built packages
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
